<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Roulette_Bot</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Icon\icons8-robot-94.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icon\Roulette_Bot_Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icon\icons8-robot-94.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Styles\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MVVM Core\MVVM Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icon\Roulette_Bot_Logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
